# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://manny.db.elephantsql.com:5432/kijustxh
    username: kijustxh
    password: M_OnDyP0dxmroe_6aAdSpa8qJdNedd7x
  # JPA properties
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# Server configuration
server:
  port: 8080
# Security configuration
security:
  user:
    name: user
password: user
